POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "test3",
  "url": "http://google.com"
}


###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/test
